services:
  # frontend:
  #   image: antoniopapa1991/frontend
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - backend
  # backend:
  #   build: .
  #   container_name: backend
  #   restart: always
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db
  db:
    image: postgres
    container_name: dbdata
    restart: always
    tty: true
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=admin
    volumes:
      - .dbdata:/var/lib/postgres/data
volumes:
  .dbdata:
    driver: local
